<?php

namespace AppBundle\Repository;

/**
 * CashRegisterDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashRegisterDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
