<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Enumerator;
use Doctrine\Common\Persistence\Mapping\ClassMetadata;
use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;

/**
 * DriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictionaryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @Słownik - lista parametrów
     * @param array $params
     * @return array
     */
    public function getParamList($params = array())
    {
        $qb = $this->createQueryBuilder('d')
            ->select("d.name as name, dc.name as category")
            ->join('d.category', 'dc');

        return $qb->getQuery()->getArrayResult();
    }
}
