<?php

namespace AppBundle\Repository;

/**
 * FirmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFirms()
    {
        // TODO : zmienić z group na aktywna umowe
        $qb = $this->createQueryBuilder('f')
            ->select("f.id, f.name, f.nip, f.phone, a.number, a.endDate , ad.street, ad.postalCode, ad.city, ad.country")
            ->leftJoin('f.agreements', 'a')
            ->leftJoin('f.address', 'ad')
            ->groupBy('f.name')
        ;

        return $qb->getQuery()->getArrayResult();
    }
}
