<?php

namespace AppBundle\Repository;

/**
 * ParamCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
