<?php

namespace AppBundle\Repository;
use Doctrine\Common\Persistence\Mapping\ClassMetadata;
use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;

/**
 * DriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerminalRepository extends \Doctrine\ORM\EntityRepository
{
    private $pdo;

    /**
     * CardRepository constructor.
     */
    public function __construct(EntityManagerInterface $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->pdo = $this->getEntityManager()->getConnection();
    }

    public function getTerminalByID($id)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.id')
            ->where('t.taxiTerminalId = :terminalID')
            ->setParameter(':terminalID', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
