security:
    encoders:
        AppBundle\Entity\User: bcrypt
        AppBundle\Entity\ApiTaxi360\Driver: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_DRIVER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username
        driver_provider:
            entity:
                class: AppBundle\Entity\ApiTaxi360\Driver
                property: licenseNumber

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        public:
#            anonymous: ~
#            pattern: ^/public
#            provider: driver_provider
#            form_login:
#                login_path: route_public_login
#                check_path: route_public_login
#                default_target_path: route_public_driver
#            logout:
#                path: public_logout
#                target: /public
        main:
            anonymous: ~
            logout_on_user_change: true
            provider: db_provider
            switch_user: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: app
                username_parameter: login[username]
                password_parameter: login[password]
            logout:
                path: logout
                target: login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                remember_me_parameter: login[remember_me]


    access_control:
        - { path: ^/public/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public, roles: ROLE_DRIVER }

        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }


        - { path: ^/, roles: ROLE_USER }
